import type { Metadata } from "next";

import "./globals.css";
import { AuthProvider } from "./_components/UserProvider";

import { CartProvider } from "./_components/CartProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <AuthProvider>
            {/* <div className="w-full"><Header /></div> */}
            {children}
          </AuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}
